### ISSUE TITLE
Use of `%kernel.project_dir%` in configuration file

### ISSUE THREAD

**Issue by witrin** [Sylius/ShopApiPlugin#377]
The following line uses `%kernel.project_dir%`:

https://github.com/Sylius/ShopApiPlugin/blob/841627750724d1ff87686d11ea3ba1ca8cdec213/src/Resources/config/services/command_requests.xml#L5 

This produces the following error in my setup:

```
App\Tests\Controller\ProductApiTest
Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "/var/www/html/src/Request" does not exist. in /var/www/html/vendor/symfony/config/FileLocator.php:44
Stack trace:
#0 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(110): Symfony\Component\Config\FileLocator->locate('/var/www/html/s...', '/var/www/html/v...', true)
#1 /var/www/html/vendor/symfony/dependency-injection/Loader/FileLoader.php(126): Symfony\Component\Config\Loader\FileLoader->glob('/*', true, NULL, false, false, Array)
#2 /var/www/html/vendor/symfony/dependency-injection/Loader/FileLoader.php(57): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('Sylius\\ShopApiP...', '/var/www/html/s...', Array)
#3 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(157): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), 'Sylius\\ShopApiP...', '%kernel.project...', Array)
#4 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(66): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinitions(Object(DOMDocument), '/var/www/html/v...', Array)
#5 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(151): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('/var/www/html/v...', NULL)
#6 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/html/v...', NULL, false, '/var/www/html/v...')
#7 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(119): Symfony\Component\Config\Loader\FileLoader->import('services/comman...', NULL, false, '/var/www/html/v...')
#8 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(56): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseImports(Object(DOMDocument), '/var/www/html/v...')
#9 /var/www/html/vendor/sylius/shop-api-plugin/src/DependencyInjection/ShopApiExtension.php(26): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('services.xml')
#10 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Sylius\ShopApiPlugin\DependencyInjection\ShopApiExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#11 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#12 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#13 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(750): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#14 /var/www/html/vendor/symfony/http-kernel/Kernel.php(544): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#16 /var/www/html/vendor/lakion/api-test-case/src/ApiTestCase.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#17 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(702): Lakion\ApiTestCase\ApiTestCase::createSharedKernel()
#18 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#19 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#20 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#21 /var/www/html/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#22 {main}

Next Symfony\Component\Config\Exception\LoaderLoadException: The file "/var/www/html/src/Request" does not exist in /var/www/html/vendor/sylius/shop-api-plugin/src/DependencyInjection/../Resources/config/services/command_requests.xml (which is being imported from "/var/www/html/vendor/sylius/shop-api-plugin/src/DependencyInjection/../Resources/config/services.xml"). in /var/www/html/vendor/symfony/config/Loader/FileLoader.php:166
Stack trace:
#0 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/html/v...', NULL, false, '/var/www/html/v...')
#1 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(119): Symfony\Component\Config\Loader\FileLoader->import('services/comman...', NULL, false, '/var/www/html/v...')
#2 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(56): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseImports(Object(DOMDocument), '/var/www/html/v...')
#3 /var/www/html/vendor/sylius/shop-api-plugin/src/DependencyInjection/ShopApiExtension.php(26): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('services.xml')
#4 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Sylius\ShopApiPlugin\DependencyInjection\ShopApiExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#5 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(750): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#8 /var/www/html/vendor/symfony/http-kernel/Kernel.php(544): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#9 /var/www/html/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#10 /var/www/html/vendor/lakion/api-test-case/src/ApiTestCase.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#11 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(702): Lakion\ApiTestCase\ApiTestCase::createSharedKernel()
#12 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#13 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#14 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#15 /var/www/html/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#16 {main}
Caused by
Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "/var/www/html/src/Request" does not exist. in /var/www/html/vendor/symfony/config/FileLocator.php:44
Stack trace:
#0 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(110): Symfony\Component\Config\FileLocator->locate('/var/www/html/s...', '/var/www/html/v...', true)
#1 /var/www/html/vendor/symfony/dependency-injection/Loader/FileLoader.php(126): Symfony\Component\Config\Loader\FileLoader->glob('/*', true, NULL, false, false, Array)
#2 /var/www/html/vendor/symfony/dependency-injection/Loader/FileLoader.php(57): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses('Sylius\\ShopApiP...', '/var/www/html/s...', Array)
#3 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(157): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses(Object(Symfony\Component\DependencyInjection\Definition), 'Sylius\\ShopApiP...', '%kernel.project...', Array)
#4 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(66): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseDefinitions(Object(DOMDocument), '/var/www/html/v...', Array)
#5 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(151): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('/var/www/html/v...', NULL)
#6 /var/www/html/vendor/symfony/config/Loader/FileLoader.php(90): Symfony\Component\Config\Loader\FileLoader->doImport('/var/www/html/v...', NULL, false, '/var/www/html/v...')
#7 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(119): Symfony\Component\Config\Loader\FileLoader->import('services/comman...', NULL, false, '/var/www/html/v...')
#8 /var/www/html/vendor/symfony/dependency-injection/Loader/XmlFileLoader.php(56): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->parseImports(Object(DOMDocument), '/var/www/html/v...')
#9 /var/www/html/vendor/sylius/shop-api-plugin/src/DependencyInjection/ShopApiExtension.php(26): Symfony\Component\DependencyInjection\Loader\XmlFileLoader->load('services.xml')
#10 /var/www/html/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(76): Sylius\ShopApiPlugin\DependencyInjection\ShopApiExtension->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#11 /var/www/html/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#12 /var/www/html/vendor/symfony/dependency-injection/Compiler/Compiler.php(95): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#13 /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php(750): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#14 /var/www/html/vendor/symfony/http-kernel/Kernel.php(544): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#15 /var/www/html/vendor/symfony/http-kernel/Kernel.php(133): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#16 /var/www/html/vendor/lakion/api-test-case/src/ApiTestCase.php(68): Symfony\Component\HttpKernel\Kernel->boot()
#17 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(702): Lakion\ApiTestCase\ApiTestCase::createSharedKernel()
#18 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(545): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#19 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(195): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#20 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(148): PHPUnit\TextUI\Command->run(Array, true)
#21 /var/www/html/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#22 {main}
```
When I'm changing https://github.com/Sylius/ShopApiPlugin/blob/841627750724d1ff87686d11ea3ba1ca8cdec213/src/Resources/config/services/command_requests.xml as in the following it works:

```
<prototype namespace="Sylius\ShopApiPlugin\Request\" resource="../../../src/Request/*" />
```

**Comment by mamazu** [comment]
What does this line do?

In the commits you mentioned the API changed their strategy how they generate Requests Objects I guess this is conflicting with your definition.

**Comment by witrin** [comment]
@mamazu I've edited my issue may be now it's more clear for you?

**Comment by mamazu** [comment]
Yeah this only makes sense in the main project but not if you use it as a dependency. Looks like a bug.
